import jsPDF from 'jspdf';
import 'jspdf-autotable';

export function generatePDF(report, presetName) {
    const doc = new jsPDF();
    const accent = [74, 222, 128];

    // Title
    doc.setFillColor(11, 18, 21);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Extinction Impact Report', 15, 25);

    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(`Ecosystem: ${presetName}`, 15, 33);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 15, 39);
    doc.text(`Engine: Lotka-Volterra Recursive Simulation`, 15, 45);

    // Divider
    doc.setDrawColor(accent[0], accent[1], accent[2]);
    doc.setLineWidth(0.5);
    doc.line(15, 50, 195, 50);

    // Removed Species
    doc.setFontSize(14);
    doc.setTextColor(239, 68, 68);
    doc.text(`Species Removed: ${report.removedSpecies}`, 15, 60);
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.text(`Role: ${report.removedRole}`, 15, 67);

    // Summary stats
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text('Summary', 15, 80);

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Stability: 100% -> ${(report.stabilityAfter * 100).toFixed(0)}%`, 15, 88);
    doc.text(`Biomass Loss: ${report.biomassLoss}%`, 15, 94);
    doc.text(`Cascade Events: ${report.cascadeChain.length}`, 15, 100);

    // Impact Table
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text('Species Impact Analysis', 15, 115);

    const tableData = report.impacts.map(imp => [
        imp.name,
        imp.before.toFixed(1),
        imp.after.toFixed(1),
        `${imp.change > 0 ? '+' : ''}${imp.change}%`,
        imp.status
    ]);

    doc.autoTable({
        startY: 120,
        head: [['Species', 'Before', 'After', 'Change', 'Status']],
        body: tableData,
        theme: 'grid',
        styles: {
            fillColor: [15, 23, 42],
            textColor: [226, 232, 240],
            lineColor: [51, 65, 85],
            fontSize: 9,
            cellPadding: 3,
            font: 'helvetica'
        },
        headStyles: {
            fillColor: [30, 41, 59],
            textColor: [accent[0], accent[1], accent[2]],
            fontStyle: 'bold',
            fontSize: 8
        },
        columnStyles: {
            3: { textColor: [239, 68, 68] },
            4: { fontStyle: 'bold' }
        }
    });

    const tableRef = doc.lastAutoTable || doc.previousAutoTable || (doc.autoTable && doc.autoTable.previous) || { finalY: 150 };
    let y = tableRef.finalY + 15;

    // Cascade Chain
    if (report.cascadeChain.length > 0) {
        doc.setFontSize(11);
        doc.setTextColor(255, 255, 255);
        doc.text('Trophic Cascade Chain', 15, y);
        y += 8;
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        const chainText = report.cascadeChain.map(ev => ev.event).join(' -> ');
        const lines = doc.splitTextToSize(chainText, 170);
        doc.text(lines, 15, y);
        y += lines.length * 5 + 10;
    }

    // Recovery Strategies
    if (y > 250) { doc.addPage(); y = 20; doc.setFillColor(11, 18, 21); doc.rect(0, 0, 210, 297, 'F'); }

    doc.setFontSize(11);
    doc.setTextColor(accent[0], accent[1], accent[2]);
    doc.text('Recovery Strategies', 15, y);
    y += 8;

    report.strategies.forEach(strat => {
        if (y > 270) { doc.addPage(); y = 20; doc.setFillColor(11, 18, 21); doc.rect(0, 0, 210, 297, 'F'); }
        doc.setFontSize(9);
        doc.setTextColor(255, 255, 255);
        doc.text(`[${strat.priority}] ${strat.type}`, 15, y);
        y += 5;
        doc.setTextColor(148, 163, 184);
        const desc = doc.splitTextToSize(strat.description, 170);
        doc.text(desc, 15, y);
        y += desc.length * 4 + 3;
        doc.setTextColor(100, 116, 139);
        doc.setFontSize(8);
        const ex = doc.splitTextToSize(`Example: ${strat.example}`, 170);
        doc.text(ex, 15, y);
        y += ex.length * 4 + 8;
    });

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(71, 85, 105);
    doc.text('Generated by Ecosystem Dynamics Lab — Lotka-Volterra Engine', 15, 290);

    doc.save(`extinction-report-${report.removedSpecies.toLowerCase().replace(/\s/g, '-')}.pdf`);
}
